#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

in_vcf="$1"
out_vcf="$2"
small_min_gq="$3"
medium_min_gq="$4"

bcftools plugin setGT  --output-type u "${in_vcf}" -- \
  --target-gt q --new-gt . \
  --include "INFO/SVTYPE = \"DUP\" & INFO/SVLEN >= 0 & INFO/SVLEN < 500 & GQ < ${small_min_gq}" \
  | bcftools plugin setGT --output-type z --output "${out_vcf}" - -- \
      --target-gt q --new-gt . \
      --include "INFO/SVTYPE = \"DUP\" & INFO/SVLEN >= 500 & INFO/SVLEN < 5000 & GQ < ${medium_min_gq}"
bcftools index --tbi "${out_vcf}"
