#!/usr/bin/env bash

# VisualizeCnvs.ExtractVariants
# Extract CNVs to visualize from a VCF.
#
# Args: <vcf> <min_size> <tsv_prefix> <variants_per_shard> <merged_intervals>

set -o errexit
set -o nounset
set -o pipefail

in_vcf="$1"
min_size="$2"
tsv_prefix="$3"
variants_per_shard="$4"
merged_intervals="$5"

tmp="$(mktemp -d "${PWD}" tmp_XXXXXXXXX)"
trap 'rm -f "${tmp}"' EXIT

bcftools view --include "(SVTYPE == \"DEL\" || SVTYPE == \"DUP\") & FILTER ~ \"PASS\" & SVLEN >= ${min_size} & GT ~ \"1\"" \
  --format '%CHROM\t%POS\t%INFO/END\t%ID\t%INFO/SVTYPE\t[%SAMPLE,]\n' "${in_vcf}" \
  | awk -F'\t' '{sub(/,$/, "", $6); print}' OFS='\t' > "${tmp}"

# merge intervals that are close to prevent duplicates when retrieving with
# tabix
awk -F'\t' '{print $1"\t"($2 - 1)"\t"$3}' "${tmp}" \
  | LC_ALL=C sort -k1,1 -k2,2n \
  | bedtools merge -i stdin -d 101 > "${merged_intervals}"

split -l "${variants_per_shard}" "${tmp}" "${tsv_prefix}"
