#!/usr/bin/env bash

# VisualizeCnvs.MergePlotTars
# Merge CNV plots into a single tar file.
#
# Args: <tar_files> <output_prefix>

set -o errexit
set -o nounset
set -o pipefail

tar_files="$1"
output_prefix="$2"

mkdir "${output_prefix}"
while read -r f; do
  tar -xzf "${f}"
  mv -t "${output_prefix}" plots/*.jpg
  rm -r plots
done < "${tar_files}"

tar -czf "${output_prefix}.tar.gz" "${output_prefix}"
