#!/usr/bin/env bash

# VisualizeCnvs.SubsetBincovMatrix
# Subset the bincov matrix to bins overlapping variants.
#
# Args: <intervals> <bincov> <output>

set -o errexit
set -o nounset
set -o pipefail

intervals="$1"
bincov="$2"
output="$3"

tmp="$(mktemp -d "${PWD}" tmp_XXXXXXXXX)"
trap 'rm -f "${tmp}"' EXIT

# need to expand the intervals so that padding can be added when plotting
cat "${intervals}" \
  | xargs cat \
  | awk -F'\t' '{s=$3 - $2; pad=int(s / 2) + 1; min=$2 - pad; $2=min < 0 ? 0 : min; $3+=pad; print}' OFS='\t' \
  | sort -k1,1 -k2,2n \
  | bedtools merge -i stdin -d 101 > "${tmp}"
tabix --print-header --regions "${tmp}" "${bincov}" | bgzip > "${output}"
tabix --zero-based --begin 2 --comment '#' --end 3 --sequence 1 "${output}"
