version: 1.2
workflows:
  - name: IndexClusteredVcfs
    subclass: WDL
    primaryDescriptorPath: /wdl/IndexClusteredVcfs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
  - name: SplitVcfByContig
    subclass: WDL
    primaryDescriptorPath: /wdl/SplitVcfByContig.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
  - name: AddEnd2ToVcf
    subclass: WDL
    primaryDescriptorPath: /wdl/AddEnd2ToVcf.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
  - name: SetGenotypesNull
    subclass: WDL
    primaryDescriptorPath: /wdl/SetGenotypesNull.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
  - name: MoveVcfFiltersToInfo
    subclass: WDL
    primaryDescriptorPath: /wdl/MoveVcfFiltersToInfo.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
  - name: SubsetVcfBySamples
    subclass: WDL
    primaryDescriptorPath: /wdl/SubsetVcfBySamples.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
  - name: MakeSitesOnlyVcf
    subclass: WDL
    primaryDescriptorPath: /wdl/MakeSitesOnlyVcf.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
