version: 1.2
workflows:
  - name: IndexClusteredVcfs
    subclass: WDL
    primaryDescriptorPath: /wdl/IndexClusteredVcfs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
  - name: SplitVcfByContig
    subclass: WDL
    primaryDescriptorPath: /wdl/SplitVcfByContig.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
  - name: AddEnd2ToVcf
    subclass: WDL
    primaryDescriptorPath: /wdl/AddEnd2ToVcf.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
