#!/usr/bin/env bash

# IndexClusteredVcfs.IndexVcf
# Index a VCF using tabix
#
# Args: <vcf>

set -o errexit
set -o nounset
set -o pipefail

vcf="$1"
vcf_bn="$(basename "${vcf}")"

# The VCF index is created in the same directory as the VCF, which could be a
# subdirectory of the current execution directory. Then, on Terra (an Cromwell)
# when the index is delocalized, it is placed in a subdirectory of the
# submission directory which could cause it to have a long path. Move the VCF
# to the current directory before indexing makes the index get delocalized to
# the top level submission directory.
mv "${vcf}" "${PWD}"
tabix "${vcf}"
