#!/usr/bin/env bash

# MakeFileFromArray.MakeFileFromArrayTask
# Make a File WDL output from an Array WDL input.
#
# Args: <input> <output>

set -o errexit
set -o nounset
set -o pipefail

# This should be a file path returned by a write_lines() call on the array
input="$1"
output="$2"

mv "${input}" "${output}"
