#!/usr/bin/env bash

# MoveVcfFiltersToInfo.MoveVcfFilters
# Move BOTHSIDES_SUPPORT, HIGH_SR_BACKGROUND, and PESR_GT_OVERDISPERSION values
# from the FILTER field to the INFO field.
#
# Args: <vcf> <output_vcf>

set -o errexit
set -o nounset
set -o pipefail

in_vcf="$1"
out_vcf="$2"

# faster to skip bcftools parsing
bgzip -cd "${in_vcf}" \
  | gawk -f /opt/gatk-sv-utils/scripts/move_vcf_filters.awk - \
  | bgzip -c > "${out_vcf}"
bcftools index --tbi "${out_vcf}"
