#!/usr/bin/env bash

# EstimateDeNovoRate.GatherGenotypes
# Gather genotypes from a VCF into a compressed TSV.
#
# Args: <vcf> <filter> <output>

set -o errexit
set -o nounset
set -o pipefail

vcf="$1"
filter="$2"
output="$3"

bcftools query --include "${filter}" \
  --format '[%SAMPLE\t%ID\t%INFO/SVTYPE\t%INFO/SVLEN\t%GT\t%GQ\n]' "${vcf}" \
  | gawk -i logging \
      'BEGIN{FS="\t"; OFS="\t"}
       $5 == "0/0" {$5 = 0; print; next}
       $5 == "1/0" || $5 == "0/1" {$5 = 1; print; next}
       $5 == "1/1" {$5 = 2; print; next}
       $5 == "./." {$5 = "NA"; print; next}
       {logging::log_err("unknown genotype in record: " $0); exit 1}' \
  | zstd -c > "${output}"
