#!/usr/bin/env bash

# SetGenotypesNull.SetGenotypesNullTask
# Set genotypes on given contigs for given samples to null.
#
# Args: <vcf> <output_vcf> <samples_list> <contigs>

set -o errexit
set -o nounset
set -o pipefail

in_vcf="$1"
out_vcf="$2"
samples="$3"
contigs="$4"

wc -l "${samples}" | read -r nsamples other
if (( nsamples == 0 )); then
  printf 'expected at least one sample. none given.\n' > /dev/stderr
  exit 1
fi

bgzip -cd "${in_vcf}" \
| gawk -f /opt/gatk-sv-utils/scripts/set_gt_null.awk "${contigs}" "${samples}" - \
| bgzip -c > "${out_vcf}"
bcftools index --tbi "${out_vcf}"
