#!/usr/bin/env bash

# SubsetVcfBySamples.GetSamplesFromFamilies
# Get the samples from families in a pedigree.
#
# Args: see get_samples_from_families.awk

set -o errexit
set -o nounset
set -o pipefail

gawk -f /opt/gatk-sv-utils/scripts/get_samples_from_families.awk "$@"
