#!/usr/bin/env bash

# AddEnd2ToVcf.AddEnd2
# Add END2 to the INFO field of intrachromosomal BND and CTX records in a VCF.
#
# Args: <vcf> <output_vcf>

set -o errexit
set -o nounset
set -o pipefail

in_vcf="$1"
out_vcf="$2"

# faster to skip bcftools parsing
bgzip -cd "${in_vcf}" \
  | gawk -f /opt/gatk-sv-utils/scripts/add_end2_to_vcf.awk - \
  | bgzip -c > "${out_vcf}"
bcftools index --tbi "${out_vcf}"
